# Generated by Django 3.0.7 on 2020-06-21 13:39

from django.db import migrations

from django.apps.registry import Apps

DEFAULT_SUPERUSER = {
    "is_active": True,
    "is_staff": True,
    "is_superuser": True,
    "password": "admin",
    "user_permissions": [],
    "username": "admin"
}


def init_superuser(apps: Apps, schema_editor):
    model = apps.get_model('users', 'user')
    users = model.objects.filter(username='admin')
    if not users.exists():
        model(**DEFAULT_SUPERUSER).save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.RunPython(init_superuser)
    ]
