# Generated by Django 3.0.7 on 2020-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('author', models.CharField(max_length=8)),
                ('rank', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.IntegerField(default=0, help_text='number of comments.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
